version: '3.7'

services:
  golangci-lint-docker-compose:
    image: golang:1.20
    container_name: golangci-lint-docker-compose
    volumes:
      - ..:/app
    command: bash /app/docker/docker-compose-lint.sh