version: '3.7'

services:
  golangci-lint-docker-compose:
    image: golang:1.18
    container_name: golangci-lint-docker-compose
    volumes:
      - ..:/app
    command: sh /app/docker/docker-compose-lint.sh