linters-settings:
  custom:
    cerrl:
      path: ../cerrl.so
      description: Checks that errors created by the cerror package are logged
linters:
  # please, do not use `enable-all`: it's deprecated and will be removed soon.
  # inverted configuration with `enable-all` and `disable` is not scalable during updates of golangci-lint
  disable-all: true
  enable:
    - cerrl
    - lll # as minimum on of the built-in linters is required

issues:
  # Excluding configuration per-path, per-linter, per-text and per-source
  exclude-rules:
    - path: _test\.go
      linters:
        - cerrl